services:
  kairos:
    image: kairosplan/kairos:latest
    container_name: kairos
    restart: unless-stopped
    ports:
      - 4321:4321
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
